#ifndef BULLET_HELL_5_CONST_H
#define BULLET_HELL_5_CONST_H

// screen
#define SCREEN_WIDTH 640.0
#define SCREEN_HEIGHT 480.0
// matematyczne
#define CORD_ORIGIN 0.0
#define PI 3.14159265
#define FULL_CIRCLE 360.0


// max danych
#define MAX_PLAYER_NAME_LENGTH 20
#define CONFIG_MAX_LINE_LENGTH 1000

// time, frequency
#define MAX_TIME_BONUS_HEALTH_DISPLAY 5000
#define MAX_TIME_HIGHLIGHT_ALIVE 4000
#define DEFAULT_ADVANCED_ATTACK_FREQUENCY 3000
#define BLOCK_EXPLOSION_ANIMATION_TIME 300
#define POINTS_CHANGE_ANIMATION 700

// life, points
#define TAKEN_LIFE_PERCENT 20
#define GIVEN_LIFE_PERCENT 30
#define INVINCIBILITY_TIME 2000
#define GIVE_POINTS 5.0
#define TAKE_POINTS 5.0

// hitboxy
#define ALL_HITBOX 1.1
#define HEAD_HITBOX 1.4
#define TORSO_HITBOX 1.2
#define LEGS_HITBOX 1



// poruszanie sie

#define DRAG 0.001
#define STEP 10.0
// speed, drag
#define MAX_SPEED 4
#define MIN_SPEED 3
#define MIN_BULLET_SPEED 1
#define MAX_BULLET_SPEED 2
#define MIN_GREATER_BULLET_SPEED 4
#define MAX_GREATER_BULLET_SPEED 6
#define MIN_SHARD_SPEED 3.5
#define MAX_SHARD_SPEED 5
#define FIREWORK_DRAG 0.005
#define GREATER_DRAG 0.03
#define SHARD_DRAG 0.02

// strzaly

#define FIREWORK_DELTA_ANGLE 40
// podzial kola
#define MIN_PARTS_OF_CIRCLE_DIVIDE 2
#define MAX_PARTS_OF_CIRCLE_DIVIDE 5
// odstepy
#define MIN_NORMAL_SPACE 5
#define MAX_NORMAL_SPACE 10
#define MIN_CORRIDOR_SPACE 30
#define MAX_CORRIDOR_SPACE 40
#define MAX_RAND_SPACE 40
// killerPattern
#define SHOOTS_KILLER_PATTERN 2
#define DELTA_KILLER_PATTERN 4



// wyswietlanie
#define NO_SCALE 1.0
#define POINTS_CHANGE_ANIMATION_SCALE 1.1
#define POINTS_SIZE_ANIMATION_SCALE 0.0016
// .._.. na ekranie gry
#define RELATIVE_POS_TIME_ELAPSED_X (0.66 * SCREEN_WIDTH)
#define RELATIVE_POS_TIME_ELAPSED_Y (0.02 * SCREEN_HEIGHT)
#define RELATIVE_POS_LEVEL_X (0.50 * SCREEN_WIDTH)
#define RELATIVE_POS_LEVEL_Y (0.07 * SCREEN_HEIGHT)
#define RELATIVE_POS_LIFE_VIEW_Y (0.97 * SCREEN_HEIGHT)
#define RELATIVE_POS_STRING_LIFE_X (0.70 * SCREEN_WIDTH)
#define RELATIVE_POS_LIFEBAR_X (0.84 * SCREEN_WIDTH)
#define POINTS_CHANGE_X (0.88 * SCREEN_WIDTH)
#define POINTS_CHANGE_Y (0.12 * SCREEN_HEIGHT)
#define RELATIVE_POS_NAME_X (0.3 * SCREEN_HEIGHT)
#define RELATIVE_POS_NAME_Y (0.7 * SCREEN_HEIGHT)
#define RELATIVE_POS_SCORES_DISPLAY_X (0.01 * SCREEN_HEIGHT)
// .._.. w menu
#define BUTTON_POSITION_X 160.0
#define DELTA_BUTTONS_POSITION_Y 31.0
#define DELTA_SCORES_DISPLAY_POSITION_Y 20



#endif //BULLET_HELL_5_CONST_H
